locale: "en-US"
title: "About"
title_separator: "-"
name: &name "Emrullah D. Çakır"
description: &description "academic webpage for Emrullah D. Çakır"
url: https://emrullahd-cakir.github.io
baseurl: ""
repository: "emrullahd-cakir/emrullahd-cakir.github.io"
future: true
read_more: "disabled"

author:
  name: "Emrullah D. Çakır"
  avatar: "profile-placeholder.svg"
  bio: "Astrophysics student"
  location: "United States"
  employer:
  email: "your.email@example.com"
  github: "emrullahd-cakir"
  googlescholar: "https://scholar.google.com/"
  orcid:

include:
  - _pages
  - files

markdown: kramdown
highlighter: rouge
encoding: UTF-8
permalink: /:categories/:title/
timezone: America/New_York

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-sitemap
  - jekyll-feed
